[env:observer]
platform = espressif32@6.9.0
board = lilygo-t-display-s3
framework = arduino
upload_port = COM11
monitor_port = COM11
upload_speed = 921600
monitor_speed = 115200
lib_extra_dirs = .vendor/T-Display-S3/lib
lib_deps = bblanchon/ArduinoJson@6.21.5
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D TOUCH_MODULES_CST_MUTUAL
